### ISSUE TITLE
Timer runs slow so subtitles fall behind video in Windows

### ISSUE THREAD

**Issue by alexhk90** [carsonip/Penguin-Subtitle-Player#11]
Penguin Subtitle Player (0.2.0) falls behind the video for me under Windows (7, 64 bit).

To reproduce, using Windows play a video in (say) VLC and the corresponding subtitles in Penguin Subtitle Player. (Note: I have seen this consistently with other applications / online video players, but VLC is free and open source so easy to use as an example.)
The time falls behind the video at a relatively constant rate of around 1 second a minute - i.e. at 5:00 in the video, Penguin Subtitle Player will be at around 4:55, at 10:00 in the video it will be at around 9:50, etc.

This appears to be an issue with the QT timer in Windows:
http://stackoverflow.com/questions/22560908/strange-accuracy-of-qtimer-with-windows-8
And might be fixed by setting the Qt::TimerType to Qt::PreciseTimer:
http://doc.qt.io/qt-5/qt.html#TimerType-enum
If it's only Windows where this happens then it's probably best to leave the setting in other OSs (it's probably quite processor intensive to use that setting), and only set it for Windows (or make it an option in the settings which defaults to on in Windows and off in other OSs).

**Comment by carsonip** [comment]
@alexhk90 thanks for reporting, I can confirm the issue. I am working on it now.
