### ISSUE TITLE
Add playback speed/multiplier feature

### ISSUE THREAD

**Issue by alexhk90** [carsonip/Penguin-Subtitle-Player#16]
Some source subtitle files are too fast/slow (perhaps due to 30/25FPS conversion) - it would be useful to set a speed for the subtitle playback (faster/slower than the actual times in the file). This could be implemented by a multiplier applied to the actual times (e.g. 1.2x the times in the file would increase the speed by 20%, 0.7x would reduce the speed by 30%, etc.).

**Comment by carsonip** [comment]
@alexhk90 that shouldn't be hard to implement. The problem is we first need a menu (e.g. right click context menu) to show the options and functions.

**Comment by alexhk90** [comment]
I see there is a new pull request #48 by @fdeloche which might implement this?

**Comment by fdeloche** [comment]
Yes, it is the purpose of it. It appears in the general preferences as it was the simplest way to add it. The preferred constants (step, precision...) have maybe to be checked with examples. If I dit it right, it is possible to reach a precision of 0.125%. To have better precision, one has to increase intervalModCounterBase (16, 32...) and set the right precision for the QDoubleSpinBox (it is set to 3 decimals but we could set it to 4).

**Comment by carsonip** [comment]
This is implemented in #49.
