### ISSUE TITLE
Add font colour option to preferences

### ISSUE THREAD

**Issue by alexhk90** [carsonip/Penguin-Subtitle-Player#17]
There is an option for font style and size, and background colour in the "Appearance" page of the preferences, but there does not appear to be a font colour option.

**Comment by carsonip** [comment]
planning to work on outlining the subtitles first, which sounds more important and useful to me. Font color customization should be easy to implement.

**Comment by alexhk90** [comment]
@carsonip Yes, I agree; the subtitles outline feature would be more useful.
Was that issue #5? It seems to have been closed for some reason.
