### ISSUE TITLE
Transparency not working in Linux with Xfce desktop environment

### ISSUE THREAD

**Issue by alexhk90** [carsonip/Penguin-Subtitle-Player#19]
The main window is not transparent under Linux with the Xfce desktop environment. 

![screenshot_2015-08-27_07-07-30](https://cloud.githubusercontent.com/assets/13845698/9513735/0f554ca4-4c8b-11e5-94d0-12f73827a1b2.png)

Instead, the window has a black background and the opacity setting appears to set the transparency of the chosen Background Color in the preferences over this black background. For example, the above has a White Background Color set at about 50% opacity.

This may provide some direction in solving the issue:
http://stackoverflow.com/questions/18316710/frameless-and-transparent-window-qt5

However, if any of these additional flags are set, regression testing should be done on at least the Linux desktop environments where the transparency already works, to make sure it doesn't fix one DE and break another.

**Comment by carsonip** [comment]
@alexhk90 i have read this SO thread before and I think that the current flags are correct. If you are free, please do the experiments with the flags in Xfce (because I don't use Xfce atm).

**Comment by alexhk90** [comment]
@carsonip Sure - I'll have a look at it.

And thank you for implementing the font color (#17) and window size and position requests (#15).

**Comment by alexhk90** [comment]
@carsonip I think you might be right - I tried changing the flags and the most I got was to make it worse by having it show a copy of the image behind the window.

On further investigation it seems this might be an issue or limitation with xfce (or qt), as I can get it to work by turning on display compositing:

![screenshot_2015-08-30_19-04-02](https://cloud.githubusercontent.com/assets/13845698/9568722/eb54aaae-4f49-11e5-8db8-2800deff41c2.png)

![screenshot_2015-08-30_19-03-18](https://cloud.githubusercontent.com/assets/13845698/9568724/ef7968f4-4f49-11e5-8647-f564e49b3006.png)

I'll see if I can find some more general information on this, but I think the issue is probably not going to be specific to Penguin Subtitle Player.

**Comment by alexhk90** [comment]
Reading up on compositing window managers it looks like this is a requirement for transparent windows:
https://en.wikipedia.org/wiki/Compositing_window_manager
https://en.wikipedia.org/wiki/Alpha_compositing

Therefore this isn't an issue - you just need to make sure you have a compositing window manager and that it is enabled.

**Comment by pepa65** [comment]
Just as a helpful pointer for Ubuntu: run dconf-editor, navigate to org.gnome.metacity, and enable compositing-manager.

**Comment by garyhouston** [comment]
With Xfce in Ubuntu 19.04, I needed:

From the Xfce Applications menu, Settings > Settings Editor
Select xfwm4 in the left panel, then scroll down the right panel to find use_compositing, and select the right-most checkbox to enable it.

**Comment by Rom888** [comment]
> Just as a helpful pointer for Ubuntu: run dconf-editor, navigate to org.gnome.metacity, and enable compositing-manager.

I can't find this key in dconf-editor on Ubuntu 20.04.
Any suggestions will be appreciated.
