### ISSUE TITLE
Window class for the app

### ISSUE THREAD

**Issue by ColdBooted** [carsonip/Penguin-Subtitle-Player#21]
Hey, :)

How do I find PenguinSubtitlePlayer window_class because I need it to remove shadows which compton draws around it? Tried with wmctrl -lx but it doesn't show in the list of opened widows.

**Comment by carsonip** [comment]
Hi, I have no idea what do you mean by "window_class", but just for your info, in order to always stay on top, we have used the `Qt::X11BypassWindowManagerHint` flag. Hopefully this will give you a clue.

**Comment by ColdBooted** [comment]
Thanks for your reply. :+1: 

I didn't know, how to define in Compton window compozer's config file the class name of your app's window in order to prevent Compton from drawing shadow around it, because I like fully transparent subtitle.  The command:

xprop WM_CLASS | cut -d\" -f2

did the trick. Now I have PSP's window without shadows without having to disable it for all windows. Thanks again. :)

![screenshot_2015-09-09_14-23-35](https://cloud.githubusercontent.com/assets/14140205/9768024/75ac5b82-5721-11e5-9051-1f751e9c1564.png)
