### ISSUE TITLE
Stop using SourceForge

### ISSUE THREAD

**Issue by forteller** [carsonip/Penguin-Subtitle-Player#26]
Lots of FLOSS developers have moved away from SF because they've started bundling Adware in with the downloads. Some adblockers has started to block browsers from even opening links to SF. You should host your downloads somewhere else too.

**Comment by carsonip** [comment]
Sorry for the late reply. I thought the bundling was opt-in, wasn't it? So do you have any suggestion of alternative?

**Comment by franklinyu** [comment]
Sorry but I am confused about "hosting" here. Since the code is already on GitHub, what else need to be "hosted"?

**Comment by carsonip** [comment]
@franklinyu Since not everyone can build the program from the code, the statically built programs have to be hosted on somewhere like SourceForge. Maybe I can also put the binaries in GitHub Release section next time. GitHub release does not support statistics though.

**Comment by franklinyu** [comment]
For statistics, how about this:

```text
https://img.shields.io/github/downloads/carsonip/Penguin-Subtitle-Player/latest/total.svg
```

which gives

![latest release](https://img.shields.io/github/downloads/carsonip/Penguin-Subtitle-Player/latest/total.svg)

I believe it comes from [GitHub API](https://help.github.com/articles/getting-the-download-count-for-your-releases/).

**Comment by carsonip** [comment]
@franklinyu Wow, this is cool. Thanks for telling me this. I'll definitely host the next version in GitHub.

**Comment by franklinyu** [comment]
Too bad GitHub does not offer an auto-build system so we still have to manually build. Travis does offer [the functionality](https://docs.travis-ci.com/user/deployment/releases) in an easy way, but it

1. requires GitHub OAuth key to be in the codebase (maybe [encrypted](https://docs.travis-ci.com/user/encryption-keys));
2. [only supports Ubuntu and OS X](https://docs.travis-ci.com/user/ci-environment), not Windows.

[Semaphore](https://semaphoreci.com/) does not add anything in the codebase, but it only supports Ubuntu. I am not familiar with [AppVeyor](https://www.appveyor.com/) or any other services.

**Comment by carsonip** [comment]
@franklinyu It is great to know Travis supports OS X. My best guess is that compiling a static build could be hard on CIs. It is still a good reminder that I should prepare a machine in the cloud to do the build. Thanks.

**Comment by carsonip** [comment]
From now on the releases will also be available at https://github.com/carsonip/Penguin-Subtitle-Player/releases other than SF.
