### ISSUE TITLE
How to use player with IceWM ?

### ISSUE THREAD

**Issue by LastOfBrunnenG** [carsonip/Penguin-Subtitle-Player#27]
Hi !

What do I need to use PSP in IceWM.  When I start it, the black window shows. As soon as I click File icon (or anything else) window disappears. The process is still running, but there is no interface.

I tried it in Xfce4 and it seems to work, i.e. File Open dialog shows up and black window is still there.

I also tried icewm-session (IceWM with session support and tray), but no dice. What do I need to do to get it running from IceWM ? I am guessing that I need to run something before PSP.

**Comment by carsonip** [comment]
@LastOfBrunnenG Any screenshots illustrating your problem? That would be helpful.

**Comment by LastOfBrunnenG** [comment]
It would be difficult to make a screenshot of an interface which disappeared from the screen. I have a normal interface until I click on folder icon (leftmost one) or configuration icon (second from the right). I tested with JWM (another window manager), works, too. Looks like it is an IceWM issue, rather than PSP. However, I was hoping you could give some advice.

I posted a problem to IceWM board, too, no answer so far. I feel it is something trivial, but don't know where to start looking for it.

**Comment by carsonip** [comment]
@LastOfBrunnenG Have you solved the issue?
