### ISSUE TITLE
Icon Visibility

### ISSUE THREAD

**Issue by JonnyTischbein** [carsonip/Penguin-Subtitle-Player#32]
![screenshot_2016-06-20_08-50-43](https://cloud.githubusercontent.com/assets/10757520/16185598/5054ae28-36c5-11e6-9533-7546a02bd24f.png)
When having no Backgroundcolor or an high opactiy the icons and the current time / ending time is not or only barely visible. 
![screenshot_2016-06-20_08-52-04](https://cloud.githubusercontent.com/assets/10757520/16185607/5b0002e6-36c5-11e6-9709-3ab7da7d5aa5.png)
(Of course the icons are visible when the window in the background is black or in general dark but most of websites and windows are white or grey)
Feature Idea: Get black borders for icons and text. Should be no differenz while watching because the UI is only shown on mouseover

**Comment by carsonip** [comment]
Merged. Thanks!
