### ISSUE TITLE
No longer shows up on the screen

### ISSUE THREAD

**Issue by Skywola** [carsonip/Penguin-Subtitle-Player#34]
Works great, but I had a problem with my mouse button, it moved the application off the screen, now the application opens, but does not show up on the screen.  Were in the heck is it storing the screen coordinates?  I check the registry and the user folder, all I see is the .exe file.  I am using Windows 8.

**Comment by carsonip** [comment]
That is unfortunate. How about clicking on the tray icon and open preferences, uncheck "remember last position and size"? Does that help?

**Comment by Skywola** [comment]
Yes, that worked like a charm, thanks!


Shawn Irwin
4802 N 12TH ST  apt 1072,
PHOENIX, AZ 85014, USA
skywola@hotmail.com<mailto:skywola@hotmail.com>
www.tachufind.com<http://www.tachufind.com>



________________________________
