### ISSUE TITLE
Support "SubStation Alpha" format

### ISSUE THREAD

**Issue by franklinyu** [carsonip/Penguin-Subtitle-Player#36]
The [SubStation Alpha](https://en.wikipedia.org/wiki/SubStation_Alpha) (`.ssa` and `.ass`) format allows font and color settings. Essential for multilingual subtitles.

**Comment by carsonip** [comment]
I would love to have `.ssa` and `.ass` support. By the time this project started, there is no simple library / conversion method for me to implement and that is why only `.srt` is supported now.

If you would like to contribute, pull requests are welcomed! Thanks.

**Comment by carsonip** [comment]
There is basic `.ssa` support now. The simple styles tags will be applied but the styles that are defined in the Styles section are ignored.
