### ISSUE TITLE
subtitle timeline issue

### ISSUE THREAD

**Issue by Gillwindy** [carsonip/Penguin-Subtitle-Player#37]
i found that if a subtitle have a later timestamp been placed (in file) before correct timestamped subtitle ,your player will ignore all the correct subtitle and only display the first subtitle it readed.

Example:

>3
>00:00:04,000 --> 00:00:05,000 
>CCC
>
>1
>00:00:01,000 --> 00:00:02,000 
>AAA
>
>2
>00:00:02,500 --> 00:00:03,500 
>BBB

your player will **ignore** AAA and BBB only display CCC at 00:00:04 .

_btw thanks for create this useful tool ,it helps a lot!_

**Comment by carsonip** [comment]
@Gillwindy Thanks for letting me know. Do you mean that the player does not work well when the subtitle order is wrong?  I think there's an easy fix to this. We can simply sort the array. Feel free to create a pull request if you can fix that.

**Comment by Gillwindy** [comment]
Yes. and sorry i dont have that skill to do so 😢

**Comment by carsonip** [comment]
No problem. Will fix this when I'm free.

**Comment by carsonip** [comment]
I'm not sure if this is a desired behavior of a subtitle player. I'll not implement this and leave this issue here until someone upvotes this issue.

**Comment by alexhk90** [comment]
I agree that this is an upstream data issue and you would not expect the player to try to fix invalid input data of this kind.
