### ISSUE TITLE
in sierra macos : subtitle font is pixelated

### ISSUE THREAD

**Issue by bomkarram** [carsonip/Penguin-Subtitle-Player#42]
Hi
My system is sierra macos and I'm working on 4k screen.
problem: subtitle font is pixelated.

Issue preview:
http://imgur.com/a/gb245

I'm big fan of your program on windows :)
Thank you

**Comment by carsonip** [comment]
Thanks for reporting the issue. Do the icons look pixelated too? I'm thinking whether it's a DPI scaling problem or QLabel anti-aliasing problem.

**Comment by carsonip** [comment]
Also, do you know how to compile and run the project? It would really help resolve the issue.

It involves downloading Qt (and Qt creator) [here](https://www.qt.io/download-open-source/), opening the project inside Qt creator and clicking the Run button at the left bottom corner.

**Comment by bomkarram** [comment]
Sorry for replaying late

**Do the icons look pixelated too?** 
Yes, they are

Two images (icons + preference) :
http://imgur.com/a/8IKo9

**do you know how to compile and run the project?** 
I can walk through it 👍

**Comment by carsonip** [comment]
I can reproduce the problem now. Working on a fix.

**Comment by carsonip** [comment]
The subtitle font is pixelated only when shadow is applied. A temporary fix is to disable the shadow.

It is a bug in Qt's QGraphicsEffect. This [issue](https://bugreports.qt.io/browse/QTBUG-60026) should be related. I will try to compile the project for macOS using Qt 5.9 though it is still in beta stage.

**Comment by carsonip** [comment]
I have recompiled it using Qt 5.9 and there is no more pixelation. I'll use Qt 5.9 to compile the next release for Mac, which will happen in a few days.

**Comment by carsonip** [comment]
@bomkarram the new release is ready. Please try v1.0.1 and let me know whether it is fixed. Thanks!
