### ISSUE TITLE
Symbols instead of Arabic characters

### ISSUE THREAD

**Issue by jiemmy** [carsonip/Penguin-Subtitle-Player#45]
Hi
when I try to load an Arabic .SRT files, the program start acting weird, show symbols instead of Arabic text and become laggy.
while the .ASS files works fine and run without a problem.
I tried to change the encoding to Arabic, System and many other options, but no luck.

**Comment by fabian5805** [comment]
try system

**Comment by carsonip** [comment]
@jiemmy Sorry for the late reply. I have been away from computer for a while. I'll look into it 2 weeks later and get back to you. Please share the SRT and ASS files so I can figure out what's going on. Thanks!

**Comment by fabian5805** [comment]
if your system has arabic language keyboard, I think it will work when you load the subtitle SRT arabic file to Penguin and choose system or utf 8. 

try tis SRT file and load it 
https://www.dropbox.com/s/bxxsba1ifh8khys/Brooklyn.Nine-Nine.S02E17.1080p.WEB-DL.DD5.1.H.264-NTb.srt?dl=0
