### ISSUE TITLE
can not run on win10

### ISSUE THREAD

**Issue by jack338c** [carsonip/Penguin-Subtitle-Player#51]
Dear 
I love this app so much,but I can 't run it on win10
Do you have any idea
thanks

**Comment by carsonip** [comment]
Are there any error messages? What's the model of your computer?

**Comment by jack338c** [comment]
say "the app can't run on your pc"
pc :Lenovo T400

**Comment by carsonip** [comment]
Can you take a screenshot of your system info? Is it a 32bit version of Windows 10?

**Comment by jack338c** [comment]
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	T400
System Manufacturer	LENOVO
System Model	7439A17
System Type	X86-based PC
System SKU	
Processor	Intel(R) Core(TM)2 Duo CPU     T9400  @ 2.53GHz, 2534 Mhz, 2 Core(s), 2 Logical Processor(s)
BIOS Version/Date	LENOVO 7UET94WW (3.24 ), 10/17/2012
SMBIOS Version	2.4
Embedded Controller Version	1.06
BIOS Mode	Legacy
BaseBoard Manufacturer	LENOVO
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.1378"
User Name	T400\t61
Time Zone	China Standard Time
Installed Physical Memory (RAM)	2.00 GB
Total Physical Memory	1.90 GB
Available Physical Memory	252 MB
Total Virtual Memory	4.42 GB
Available Virtual Memory	0.98 GB
Page File Space	2.53 GB
Page File	C:\pagefile.sys
Device Guard Virtualization based security	Not enabled
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	No
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

**Comment by carsonip** [comment]
Thanks for the detailed reply. Yes it it 32bit and I think I compiled the program for 64bit systems. I'll compile it for 32bit systems later so that you can use it. Thanks.

**Comment by jack338c** [comment]
@carsonip 
Awesome ，thank you very much ！

**Comment by carsonip** [comment]
Hopefully I'll have time to do it during the weekend.

**Comment by carsonip** [comment]
Since libraries are statically linked, I may have to compile everything all over again. That takes time. Let's see if I can get you a 32bit version of it during the weekend.

**Comment by jack338c** [comment]
It's ok
I'd like waiting for you when you have time to make it

Thank you

**Comment by carsonip** [comment]
Hi @jack338c, please check whether https://github.com/carsonip/Penguin-Subtitle-Player/releases/download/v1.1.0/PenguinSubtitlePlayer-Windows_x86.zip works for you.

**Comment by jack338c** [comment]
Ok I Will
Talk to you soon

**Comment by jack338c** [comment]
Hi *Pengu*
*it's working now *
*thank you very much !*
*Cheers*

**Comment by carsonip** [comment]
Great to know!
