### ISSUE TITLE
Subtitle Disappeared when in Full screen mode

### ISSUE THREAD

**Issue by lc700x** [carsonip/Penguin-Subtitle-Player#52]
I'm using the penguin-subtitle-player on my windows 10 laptop, when I change my player into full screen mode, the subtitle just disappears. Would  you please make it pinned even in full screen mode? Thanks.

**Comment by carsonip** [comment]
Thanks for creating an issue. 
May I ask what player is it? If it is some system-specific full screen mode, I'm afraid it may be very hard if not impossible to fix it, since the subtitle player is just a normal window which requests to be on top of other normal windows.

**Comment by lc700x** [comment]
Oh, I usually watch videos with the movies&TV player pre-installed in windows 10, and sometimes use youtube in Egde browser. When I turn into full screen mode, the window may be covered behind.

**Comment by lc700x** [comment]
Haha, maybe it's better for me to use desktop players or browsers to prevent this. Thanks for your kind enquiry.

**Comment by carsonip** [comment]
Then yes, in your situation, the subtitle player should not work. I just tried with Edge. Try other browsers like Firefox or Chrome.
For offline videos, if you place the srt file next to your video file and play the video using a proper video player (e.g. VLC, MPC-HC), the video player will display the subtitle anyway.

**Comment by lc700x** [comment]
OK, thanks for your suggestions!
