### ISSUE TITLE
Arabic subtitles doesn't work 

### ISSUE THREAD

**Issue by simocharfaoui** [carsonip/Penguin-Subtitle-Player#53]
i tried to load a .srt arabic subtitle but it only shows me symbols 
the problem is when i change writing system, it doesn't save the changes despite i'm clicking the ok 
please is there any solution ?

**Comment by carsonip** [comment]
Hi, care to upload the .srt so that I can reroduce the issue? It would be useful for me to find the cause. Thanks.

**Comment by simocharfaoui** [comment]
thanks for your reply i've found the problem
the problem was the encoding of the .srt file and it was ANSI, i converted it to UTF-8 online and it worked !
sorry to bother you and i really like your program 
cheer !

**Comment by carsonip** [comment]
Good to know. Thanks!
