### ISSUE TITLE
I want to get a button to enter the specified time Then jump to the time I entered

### ISSUE THREAD

**Issue by huanxueshen** [carsonip/Penguin-Subtitle-Player#56]
I want to get a button to enter the specified time
Then jump to the time I entered #

**Comment by carsonip** [comment]
Hi @huanxueshen, this is a great suggestion. I'm quite busy recently but I will certainly implement this when I have time. Thanks!

**Comment by huanxueshen** [comment]
> 嗨@huanxueshen，这是一个很好的建议。我最近很忙，但是当我有空的时候我肯定会实现这个。谢谢！
Thank you for understanding
Because I know that it is very difficult to implement this function.
Please be sure to help me achieve this without delaying my body.
Otherwise I will be very upset
Thank you

**Comment by huanxueshen** [comment]
You may not understand Google Translate
I will send you a Chinese and Japanese.
谢谢您的理解
因为我知道实现这个功能非常困难。
请务必在不拖延身体的情况下帮助我实现这一目标。
否则我会非常沮丧
谢谢
ご理解いただきありがとうございます。
この機能を実装するのは非常に難しいことを私は知っているからです。
私は私の体を遅らせることなくこれを達成するのを手伝ってください。
そうでなければ私は非常に落ち込んでいるでしょう
ありがとう

**Comment by huanxueshen** [comment]
> 您可能无法理解谷歌翻译
> 我将向您发送中文和日文。
> 谢谢您的理解
> 因为我知道实现这个功能非常困难。
> 请务必在不拖延身体的情况下帮助我实现这一目标。
> 否则我会非常沮丧
> 谢谢
> ご理解いただきありがとうございます。
> この机能を実装するのは非常に难しいことを私は知っているからです。
> 私は私の体を遅らせることなくこれを达成するのを手伝ってください。
> そうでなければは私に非常ち落込んでいるでしょう
> ありがとう

这样就好了

**Comment by huanxueshen** [comment]
Are you okay, body?

**Comment by huanxueshen** [comment]
hey

**Comment by carsonip** [comment]
I have added the feature. Please be reminded that this is an open source project and I do not develop and maintain it for profit. I do this in my spare time. I will build and release a new version soon.

**Comment by huanxueshen** [comment]
https://github.com/carsonip/Penguin-Subtitle-Player/issues/56#issuecomment-451658857

**Comment by carsonip** [comment]
@huanxueshen New build is out. Feel free to try out the feature you requested.

**Comment by huanxueshen** [comment]
> @huanxueshen New build is out. Feel free to try out the feature you requested.

Thank you
