### ISSUE TITLE
Where is the software settings saved? I changed a new computer. I want to set up the software and transfer it to the new computer.

### ISSUE THREAD

**Issue by huanxueshen** [carsonip/Penguin-Subtitle-Player#58]
Where is the software settings saved?
I changed a new computer. I want to set up the software and transfer it to the new computer.

**Comment by carsonip** [comment]
According to [http://doc.qt.io/qt-5/qsettings.html](http://doc.qt.io/qt-5/qsettings.html), 
> Users normally expect an application to remember its settings (window sizes and positions, options, etc.) across sessions. This information is often stored in the system registry on Windows, and in property list files on macOS and iOS. On Unix systems, in the absence of a standard, many applications (including the KDE applications) use INI text files.
