### ISSUE TITLE
ps player is not appearing

### ISSUE THREAD

**Issue by fabian5805** [carsonip/Penguin-Subtitle-Player#60]
penguin subtitle player is not visible at all in my windows 7 64bit . I downloaded every nessassry thing visual 2013 c++

**Comment by carsonip** [comment]
Hi @fabian5805, does that happen even with the older version of Penguin Subtitle Player? Also I don't think Visual C++ is not required because the software is compiled statically.

**Comment by fabian5805** [comment]
I have tried all the versions <<<< I love this subtitle player>>>>
I have formatted my windows and alomost everything is different < I doubt my windows :(
maybe my windows version is the crap one here, 
all respect to you Carsonip,, you the best

**Comment by carsonip** [comment]
Is your problem resolved now?
