### ISSUE TITLE
Can it be used as a browser to directly get the video of the webpage to load subtitles below？

### ISSUE THREAD

**Issue by huanxueshen** [carsonip/Penguin-Subtitle-Player#62]
Can it be used as a browser to directly get the video of the webpage to load subtitles below？

**Comment by carsonip** [comment]
Thanks for your suggestion. It is a creative idea for Penguin Subtitle Player to be a browser, but it would require too much engineering effort both to develop and maintain. Therefore, the requested feature will not be implemented in this project. Anyone who feels interested may integrate PSP and browser in their own project.
