### ISSUE TITLE
When I go to load the subtitles the video I'm watching doesn't show up in the files

### ISSUE THREAD

**Issue by KitKat909** [carsonip/Penguin-Subtitle-Player#64]
So I watched a video on YouTube on how to set it up and it's not letting me load it to the video I'm watching. I will press on the file icon in the top left corner and it takes me to my files and I look all through it and I cant find the video to load the subtitles to. Please Help!

**Comment by carsonip** [comment]
Hello @KitKat909 you have to download the subtitle file by yourself. You may need to search for it on google, download it and then load it in the software.
