### ISSUE TITLE
how to see subtitles in spanish

### ISSUE THREAD

**Issue by ariellachter** [carsonip/Penguin-Subtitle-Player#66]
I don't see well subtitles in spanish, I edit penguinsubtitleplayer.pro , but I don't understan how do that

**Comment by carsonip** [comment]
Hi @ariellachter, that is not how you see subtitles in Spanish. Penguin Subtitle Player supports subtitles in different languages / encodings out of the box. In case you have difficulty opening a Spanish subtitle file, please let me know the specific problem you are facing (e.g. the subtitle files is not loading / some characters are not showing) so I can help you with that.
