### ISSUE TITLE
somtime the next and previousbuttons error

### ISSUE THREAD

**Issue by tynylove** [carsonip/Penguin-Subtitle-Player#68]
When I goto by entering the time then the next and previous button ussually have error, it take back to begin (the first line of the subtitle file).
Thank you about your helpfull software
And It'll extremily great if it can have mode to reacognize the time area on screen to syns the subtitle or reacognize play/pause button or slide bar of online video player on screen.

**Comment by carsonip** [comment]
Thanks for reporting an issue. 

> When I goto by entering the time then the next and previous button ussually have error, it take back to begin (the first line of the subtitle file).

Does this happen with a particular subtitle file? I do recognize that the next button is a bit too close to the timeline, making it very easy to click on the beginning on the timeline. Is that what you are experiencing?

> And It'll extremily great if it can have mode to reacognize the time area on screen to syns the subtitle or reacognize play/pause button or slide bar of online video player on screen.

This is a feature request that is out of the scope of the project. There is no plans on implementing this feature.

**Comment by tynylove** [comment]
I have checked with two files,
You could watch the video
https://photos.app.goo.gl/f2iTUhZXKPteHU576
Thank for your reply!

**Comment by carsonip** [comment]
Thanks for the video. It is the best way to illustrate the problem. It is clear that there's a problem.

What's the version of Penguin Subtitle Player you are using? I'll try to reproduce this in my computer and get back to you.

**Comment by carsonip** [comment]
@tynylove Yes I can reproduce the issue on my end. I'll let you know when I fix the bug.

**Comment by carsonip** [comment]
Hi @tynylove, fix for the the issue is ready. I'll let you know when there is a new release.

**Comment by tynylove** [comment]
Great! thank you and I'll wait a new release.

**Comment by carsonip** [comment]
Hi @tynylove, v1.3.0 is released! Please let me know if it solved your problem.
