### ISSUE TITLE
Font Problems, special characters

### ISSUE THREAD

**Issue by Mallobag** [carsonip/Penguin-Subtitle-Player#69]
Hi, 
it seems like no matter which font i use, special characters from the slavic languages will not be shown.

Like 

A	Á	B	C	Č	D	Ď	E	É	Ě	F	G	H	Ch	I	Í	J	K	L	M	N	Ň	O	Ó	P	Q	R	Ř	S	Š	T	Ť	U	Ú	Ů	V	W	X	Y	Ý	Z	Ž
a	á	b	c	č	d	ď	e	é	ě	f	g	h	ch	i	í	j	k	l	m	n	ň	o	ó	p	q	r	ř	s	š	t	ť	u	ú	ů	v	w	x	y	ý	z	ž

Is that a program problem or a system problem.

**Comment by carsonip** [comment]
That's weird. This is a big problem. Are you sure that the font you selected support slavic characters? Also, are you using Windows, MacOS or Linux? Please check which font in your system support slavic characters and then pick that font in the program.
