### ISSUE TITLE
Feature request: Synchronization with next-click-counts hotkey

### ISSUE THREAD

**Issue by leonardmitri** [carsonip/Penguin-Subtitle-Player#76]
Just like in the alternative -Subtitle buddy- adding the next-click-counts to the video player and the subtitles so they play at the same time would be much easier.
Ive loving this penguin so far!

**Comment by carsonip** [comment]
Thanks for your support! I'll have to look into the feature and see if it is good/feasible to add to Penguin Subtitle Player.

**Comment by leonardmitri** [comment]
Thank you for your work!!!

**Comment by EmilJunker** [comment]
Any update on this? I think it would be a useful feature.

Maybe this could be implemented via the QEvent::FocusOut event. So when next-click-counts is activated and I click the play button, it shouldn't start playing right away but wait until the window loses focus (i.e. I click somewhere outside the window). 

Maybe this can help (different use case but similar idea):
https://www.qtcentre.org/threads/20642-How-to-get-mouse-click-events-outside-the-Qt-window

**Comment by EmilJunker** [comment]
@carsonip
Thank you so much for this neat feature!

> starts the timer after the first click outside of the subtitle player for easier sync between video player and subtitle player. Activate this feature by right clicking on the play button.

Would it be possible to also add "next click counts" for pausing? So when I right click the pause button, it waits for the next click before it actually pauses.
