### ISSUE TITLE
Check if AUR build is working after uchardet git submodule migration

### ISSUE THREAD

**Issue by carsonip** [carsonip/Penguin-Subtitle-Player#85]
Since we have added uchardet as a git submodule in master, it may affect builds.
I see that projects out there have specific lines for submodule handling in PKGBUILD: https://github.com/RLovelett/swift-aur/blob/master/PKGBUILD#L93

@alexhk90 Could you confirm whether the AUR build is working for master? If not, can we fix it? Thanks

**Comment by alexhk90** [comment]
@carsonip Thank you for the note. The AUR build was broken due to uchardet so I added the line for submodule handling following the example linked and it should now be fixed (confirmed working with version 1.4.0): 
https://aur.archlinux.org/packages/penguin-subtitle-player-git/

**Comment by carsonip** [comment]
@alexhk90 Thanks so much for the swift action! Really appreciate it!
