### ISSUE TITLE
Speed factor spin box step value

### ISSUE THREAD

**Issue by EmilJunker** [carsonip/Penguin-Subtitle-Player#86]
The step value of the "speed factor" spin box in General preferences is set to 0.002, so it increases/decreases by this amount when clicking the up/down buttons.

https://github.com/carsonip/Penguin-Subtitle-Player/blob/5112bb55a3e8932fc4d102a2d223f1256646d454/src/prefconstants.h#L18

Is there a particular reason why it is set to 0.002 instead of 0.001? 

I'm asking because recently I was watching a movie where after a while I noticed the audio was slightly lagging behind the subtitles. I then tried out different speed factors for the subtitles and eventually figured out that I had to set it to 0.999 for the video/audio and subtitles to be synchronized.

Since the value can only increase/decrease by 0.002, I had to enter this value manually (which was annoying because I only had a mouse but no keyboard connected, so I had to get up from the couch and walk over to my laptop that was connected to the TV 😂). Anyway, this all would have been a lot easier if the step value was 0.001. Any chance this could be changed?

**Comment by carsonip** [comment]
Sorry for the late reply. There was no specific reason to have step 0.002 instead of 0.001, and now I think that 0.001 may be less confusing for most people. It is now changed and will be available in the next release. Your use case is very special and I'm glad you find this feature useful!
