### ISSUE TITLE
Linux Binary does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by anishmittal2020** [carsonip/Penguin-Subtitle-Player#87]
I am getting the following error:

![image](https://user-images.githubusercontent.com/42092626/132141384-fd5003be-0469-46c1-ac87-e5974c07d8f2.png)

What should I do?

**Comment by carsonip** [comment]
@anishmittal2020 I realize sharing binary executable is actually not a good idea to distribute a software for Linux. I'm sorry it didn't work for you. Do you mind using snaps? https://snapcraft.io/penguin-subtitle-player

**Comment by anishmittal2020** [comment]
I execute it from command line, then it works.

**Comment by carsonip** [comment]
Great to know, closing
