### ISSUE TITLE
Charset Detection window doesnt show on top of player

### ISSUE THREAD

**Issue by tstrul1** [carsonip/Penguin-Subtitle-Player#9]
Main window is ok but when i choose srt file the charset detection window is hidden behind the player
(Checked with PowerDVD 15)

**Comment by carsonip** [comment]
@tstrul1 thanks for reporting! Do you mean the charset choosing dialog is behind the player(PowerDVD)? Is the player in full screen mode?

**Comment by tstrul1** [comment]
Yes, PowerDVD is in full screen mode.
When I open penguin subtitle player it opens on top of powerDVD but after i choose an srt file the dialog opens behind powerDVD and I need to minimize/quit full screen mode in order to press "OK".
If it is too difficult to implement maybe consider choosing "Default charset" in players settings and when i choose one, the dialog will not pop out.

**Comment by carsonip** [comment]
@tstrul1 No problem. Will add an option in the preferences such that the subtitle player uses the detected charset.

**Comment by tstrul1** [comment]
Thank you very much! I appreciate it :)
