### ISSUE TITLE
there is something wrong about the time.

### ISSUE THREAD

**Issue by Mingtu2019** [carsonip/Penguin-Subtitle-Player#94]
When I load the subtitles, its time is wrong. It cannot load all subtitles.
The original subtitles are 45 minutes, and the loaded subtitles are less than 4 minutes. I don't know how to solve it, please help, thank you very much. ——From Google Translate

change .txt to .ass

[Doctor.Who.2005.S01E02.1080p.BluRay.x264-SHORTBREHD.ChsEngA.ass.txt](https://github.com/carsonip/Penguin-Subtitle-Player/files/7475789/Doctor.Who.2005.S01E02.1080p.BluRay.x264-SHORTBREHD.ChsEngA.ass.txt)

**Comment by carsonip** [comment]
Thanks. Can confirm the bug. Your subtitle file does not have the timeline sorted and Penguin Subtitle Player does not handle that.

It is somehow related to #89

**Comment by Mingtu2019** [comment]
> Thanks. Can confirm the bug. Your subtitle file does not have the timeline sorted and Penguin Subtitle Player does not handle that.
> 
> It is somehow related to #89

thank you for your reply. In addition, subtitles like the one below cannot be loaded at all. After choosing to load this subtitle, nothing happened, no timeline, no subtitles, and nothing.
Thanks again! ——From Google Translate

change .txt to .srt

[doctor.who.2005.s01e02.720p.bluray.x264-shortbrehd.srt.txt](https://github.com/carsonip/Penguin-Subtitle-Player/files/7480868/doctor.who.2005.s01e02.720p.bluray.x264-shortbrehd.srt.txt)

**Comment by carsonip** [comment]
Please change the file extension from `.srt` to `.ass` and it should work. But it still suffers from the bug you reported and results in a 4 minute timeline.

**Comment by Mingtu2019** [comment]
> Please change the file extension from `.srt` to `.ass` and it should work. But it still suffers from the bug you reported and results in a 4 minute timeline.

Ok, I'll try. Thanks you.

**Comment by Mingtu2019** [comment]
> Please change the file extension from `.srt` to `.ass` and it should work. But it still suffers from the bug you reported and results in a 4 minute timeline.

Ok, I'll try. Thanks you.
